/** Common cities in Baden-Württemberg for rule-based location extraction */
export const BW_CITIES = [
  'Stuttgart',
  'Karlsruhe',
  'Mannheim',
  'Heidelberg',
  'Freiburg',
  'Ulm',
  'Tübingen',
  'Reutlingen',
  'Heilbronn',
  'Pforzheim',
  'Konstanz',
  'Offenburg',
  'Villingen-Schwenningen',
  'Aalen',
  'Esslingen',
  'Ludwigsburg',
  'Ravensburg',
  'Friedrichshafen',
  'Göppingen',
  'Schwäbisch Gmünd',
  'Lörrach',
  'Heidenheim',
  'Singen',
  'Böblingen',
  'Waiblingen',
  'Rastatt',
  'Baden-Baden',
  'Bruchsal',
  'Leonberg',
  'Filderstadt',
  'Weinheim',
  'Neckarsulm',
  'Bietigheim-Bissingen',
  'Schwetzingen',
  'Hockenheim',
  'Ettlingen',
  'Rheinfelden',
  'Lahr',
  'Kehl',
  'Biberach',
  'Sigmaringen',
  'Albstadt',
  'Balingen',
  'Calw',
  'Rottweil',
  'Vaihingen',
  'Metzingen',
  'Nürtingen',
  'Herrenberg',
  'Kirchheim',
  'Backnang',
  'Crailsheim',
  'Schwäbisch Hall',
  'Biberach an der Riß',
] as const;

const escaped = BW_CITIES.map((c) => c.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));

export const BW_CITY_REGEX = new RegExp(`\\b(${escaped.join('|')})\\b`, 'gi');
